import discord
from discord.ext import commands
import asyncio
import os
import sys
import io
import uuid
import traceback
import requests # Needed to download image from URL
from concurrent.futures import ThreadPoolExecutor # For type hint
from together import Together # Import the Together library

# Import necessary functions from other modules
# NOTE: Using lightweight R2 upload via boto3 (not from app4)
import boto3
from botocore.client import Config


def upload_to_r2(file_path: str, destination: str = None) -> str:
    """Upload file to R2 (lightweight implementation)"""
    import os
    from dotenv import load_dotenv
    load_dotenv()
    
    # Get R2 credentials
    r2_access_key = os.getenv('R2_ACCESS_KEY_ID')
    r2_secret_key = os.getenv('R2_SECRET_ACCESS_KEY')
    r2_endpoint = os.getenv('R2_ENDPOINT_URL')
    r2_bucket = os.getenv('R2_BUCKET_NAME')
    
    if not all([r2_access_key, r2_secret_key, r2_endpoint, r2_bucket]):
        raise Exception("Missing R2 credentials")
    
    # Create R2 client
    s3 = boto3.client('s3',
        endpoint_url=r2_endpoint,
        aws_access_key_id=r2_access_key,
        aws_secret_access_key=r2_secret_key,
        region_name='auto',
        config=Config(s3={'addressing_style': 'virtual'})
    )
    
    # Determine destination filename
    if destination is None:
        destination = os.path.basename(file_path)
    
    # Upload
    s3.upload_file(file_path, r2_bucket, destination)
    
    # Return public URL
    return f"{r2_endpoint}/{r2_bucket}/{destination}"

class UtilityCog(commands.Cog):
    """Cog for miscellaneous utility commands."""
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        # Access executor via self.bot.executor

    @commands.command(
        name='flux',
        help='Generate an image using FLUX.1-schnell (via Together API) and upload to R2',
        description='Generates an image via Together API, downloads it, uploads to R2, and returns the R2 URL.',
        usage='!flux <prompt>',
        brief='!flux <prompt>'
    )
    async def flux_command(self, ctx, *, prompt: str):
        if not isinstance(ctx.channel, discord.DMChannel):
            await ctx.send("This command can only be used in DMs.")
            return

        # --- Use Together AI API ---
        await ctx.send("Generating image using Together AI (FLUX.1-schnell-Free). This may take a moment...")

        # Get API key - **Replace with os.getenv('TOGETHER_API_KEY') in production**
        # together_api_key = os.getenv('TOGETHER_API_KEY')
        together_api_key = "952eb8f1c78a7502a27016a7878fe6690437c933ed6bd43964de4645ef62f956" # Use provided key for now

        if not together_api_key:
            await ctx.send("Error: TOGETHER_API_KEY not found in environment variables.")
            return

        # Parameters for the API call
        model = "black-forest-labs/FLUX.1-schnell-Free"
        steps = 4 # Corrected as per feedback
        n = 1 # Generate 1 image for the bot command
 
        loop = asyncio.get_event_loop()
        image_url = None # Variable to store the result URL

        try:
            # Initialize the Together client
            client = Together(api_key=together_api_key)

            # Run the blocking API call in the executor
            response = await loop.run_in_executor(
                self.bot.executor,
                lambda: client.images.generate(
                    prompt=prompt,
                    model=model,
                    steps=steps,
                    n=n
                    # width/height might not be supported by all models or this endpoint version
                )
            )

            # Process the response - expecting a URL
            if response and response.data:
                if len(response.data) > 0 and hasattr(response.data[0], 'url') and response.data[0].url:
                    image_url = response.data[0].url
                    # Send a generic message WITHOUT the long URL
                    await ctx.send("Image generated by API. Downloading and uploading to R2...")
 
                     # Download the image from the URL
                    try:
                        img_response = await loop.run_in_executor(
                            self.bot.executor,
                            lambda: requests.get(image_url, timeout=60, stream=True) # Use stream=True for potentially large images
                        )
                        img_response.raise_for_status() # Check for download errors

                        # Read content into BytesIO
                        image_data_io = io.BytesIO(img_response.content)
                        
                        # Upload to R2
                        filename_base = f"flux_together_{uuid.uuid4()}"
                        r2_url = await loop.run_in_executor(
                            self.bot.executor,
                            lambda: upload_to_r2(image_data_io, filename_base, file_extension='png') # Assuming PNG, might need to check content-type
                        )

                        if r2_url:
                            await ctx.send(f"Image uploaded successfully. Here's your R2 URL: {r2_url}")
                        else:
                            await ctx.send("Failed to upload the downloaded image to R2.")

                    except requests.exceptions.RequestException as download_err:
                        await ctx.send(f"Error downloading image from API URL: {download_err}")
                        print(f"Error downloading image from {image_url}: {download_err}", file=sys.stderr)
                    except Exception as upload_err:
                        await ctx.send(f"Error uploading image to R2: {upload_err}")
                        print(f"R2 Upload Error: {upload_err}", file=sys.stderr)
                        traceback.print_exc(file=sys.stderr)

                # Handle case where API might return base64 unexpectedly
                elif len(response.data) > 0 and hasattr(response.data[0], 'b64_json') and response.data[0].b64_json:
                     await ctx.send("API returned base64 data instead of URL. Attempting to process...")
                     # (Optional: Add base64 decoding and upload logic here if needed as fallback)
                     print("Received b64_json, expected url.")
                else:
                    await ctx.send("API response did not contain the expected image URL or data.")
                    print(f"Unexpected Together API response data format: {response.data}")
            else:
                await ctx.send("Image generation failed. No data received from API.")
                print(f"Empty or invalid response from Together API: {response}")

        except Exception as e:
            # Catch potential errors from the Together client or other issues
            await ctx.send(f"An error occurred during image generation: {str(e)}")
            print(f"Error in !flux command (Together API): {e}", file=sys.stderr)
            # Check if it's an API error from the library
            if "response" in dir(e): # Simple check if it might have response details
                 print(f"API Error details (if available): {e.response}")
            traceback.print_exc(file=sys.stderr)

# The mandatory setup function called by discord.py when loading the Cog
async def setup(bot: commands.Bot):
    await bot.add_cog(UtilityCog(bot))
    print("UtilityCog loaded.") # Optional confirmation message